FROM openhd/armbian_20.08_buster_arm64:v1

RUN apt update

COPY install_dep.sh /data/install_dep.sh

RUN /data/install_dep.sh

RUN apt -y install git

RUN apt -y install ruby-dev

RUN apt -y install python-pip python-setuptools

RUN apt -y purge python-configparser

RUN gem install fpm

RUN pip install cloudsmith-cli

COPY . /data/

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh arm64 debian buster docker
