FROM openhd/2018-10-09-raspbian-stretch-lite:v1  

RUN apt update

COPY install_dep.sh /data/install_dep.sh

RUN /data/install_dep.sh

RUN apt -y install git

RUN apt -y install ruby-dev

RUN apt -y install python-pip

RUN apt -y purge python-configparser

RUN gem install fpm

RUN pip install cloudsmith-cli==0.23.0

COPY . /data/

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh pi stretch docker
