FROM ghcr.io/openhd/x86-ubuntu-bionic:18.04

RUN apt update

COPY install_dep.sh /data/install_dep.sh

RUN /data/install_dep.sh

COPY . /data/

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh x86_64 ubuntu bionic docker
