FROM openhd/2018-10-09-raspbian-stretch-lite:v1  

RUN apt update

COPY install_dep.sh /data/install_dep.sh

RUN /data/install_dep.sh

RUN apt -y install git
RUN apt -y install ruby-dev
RUN apt -y install python-pip
RUN apt -y purge python-configparser
RUN apt -y install \
            build-essential autotools-dev automake libtool autoconf \
            libpcap-dev libpng-dev libsdl2-dev libsdl1.2-dev libconfig++-dev \
            libreadline-dev libjpeg8-dev libusb-1.0-0-dev libsodium-dev \
            libfontconfig1-dev libfreetype6-dev ttf-dejavu-core \
            libboost-dev libboost-program-options-dev libboost-system-dev libasio-dev libboost-chrono-dev \
            libboost-regex-dev libboost-filesystem-dev libboost-thread-dev wiringpi indent

RUN gem install --no-document fpm
RUN pip install --upgrade cloudsmith-cli

WORKDIR /src

ARG CLOUDSMITH_API_KEY=000000000000
RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

ENTRYPOINT ["./package.sh"]
CMD ["pi", "stretch", "docker"]

VOLUME /src
