FROM openhd/2020-05-27-raspios-buster-lite-armhf:v1

COPY . /data/

RUN apt update

RUN apt -y install git

RUN apt -y install ruby-dev

RUN apt -y install python3-pip

RUN apt -y purge python-configparser

RUN gem install fpm

RUN pip3 install cloudsmith-cli

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh pi buster docker
