sonar.projectKey=OpenHD_Open.HD
sonar.organization=openhd

sonar.sources=OpenHD
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=coverage.xml

sonar.exclusions=OpenHD/ohd_common/lib/json/**/*, \
                 OpenHD/ohd_common/lib/spdlog/**/*, \
                 deployment/**/*, \
                 Buildroot/**/*, \
                 vcpkg/**/*, \
                 plugins/topotek/**/*
