// Generated by tools/gen_camera_registry.py. Do not edit by hand.
#pragma once

#include <cstddef>
#include <string>

#include "openhd_platform.h"

namespace openhd {
namespace camera_registry {

static constexpr int X_CAM_TYPE_DUMMY_SW = 0;
static constexpr int X_CAM_TYPE_EXTERNAL = 2;
static constexpr int X_CAM_TYPE_EXTERNAL_IP = 3;
static constexpr int X_CAM_TYPE_DEVELOPMENT_FILESRC = 4;
static constexpr int X_CAM_TYPE_USB_GENERIC = 10;
static constexpr int X_CAM_TYPE_USB_INFIRAY = 11;
static constexpr int X_CAM_TYPE_USB_INFIRAY_T2 = 12;
static constexpr int X_CAM_TYPE_USB_INFIRAY_X2 = 13;
static constexpr int X_CAM_TYPE_USB_INFIRAY_P2_PRO = 14;
static constexpr int X_CAM_TYPE_USB_FLIR_VUE = 15;
static constexpr int X_CAM_TYPE_USB_FLIR_BOSON = 16;
static constexpr int X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI = 20;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647 = 30;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219 = 31;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708 = 32;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477 = 33;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708 = 40;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519 = 41;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M = 42;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462 = 43;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327 = 44;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX290 = 45;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI = 46;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662 = 47;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415 = 48;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_2MP = 60;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307 = 61;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132 = 62;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM = 63;
static constexpr int X_CAM_TYPE_X20_HDZERO_GENERIC = 70;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_V1 = 71;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_V2 = 72;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_V3 = 73;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90 = 74;
static constexpr int X_CAM_TYPE_X20_OHD_Jaguar = 75;
static constexpr int X_CAM_TYPE_X21_OHD_Jaguar = 76;
static constexpr int X_CAM_TYPE_A733_IMX415 = 77;
static constexpr int X_CAM_TYPE_A733_IMX219 = 78;
static constexpr int X_CAM_TYPE_A733_IMX214 = 79;
static constexpr int X_CAM_TYPE_ROCK_5_HDMI_IN = 80;
static constexpr int X_CAM_TYPE_ROCK_5_OV5647 = 81;
static constexpr int X_CAM_TYPE_ROCK_5_IMX219 = 82;
static constexpr int X_CAM_TYPE_ROCK_5_IMX708 = 83;
static constexpr int X_CAM_TYPE_ROCK_5_IMX462 = 84;
static constexpr int X_CAM_TYPE_ROCK_5_IMX415 = 85;
static constexpr int X_CAM_TYPE_ROCK_5_IMX477 = 86;
static constexpr int X_CAM_TYPE_ROCK_5_IMX519 = 87;
static constexpr int X_CAM_TYPE_ROCK_5_OHD_Jaguar = 88;
static constexpr int X_CAM_TYPE_ROCK_3_HDMI_IN = 90;
static constexpr int X_CAM_TYPE_ROCK_3_OV5647 = 91;
static constexpr int X_CAM_TYPE_ROCK_3_IMX219 = 92;
static constexpr int X_CAM_TYPE_ROCK_3_IMX708 = 93;
static constexpr int X_CAM_TYPE_ROCK_3_IMX462 = 94;
static constexpr int X_CAM_TYPE_ROCK_3_IMX519 = 95;
static constexpr int X_CAM_TYPE_ROCK_3_OHD_Jaguar = 96;
static constexpr int X_CAM_TYPE_ROCK_3_VEYE = 97;
static constexpr int X_CAM_TYPE_NVIDIA_XAVIER_IMX577 = 101;
static constexpr int X_CAM_TYPE_OPENIPC_GENERIC = 110;
static constexpr int X_CAM_TYPE_QC_IMX577 = 120;
static constexpr int X_CAM_TYPE_QC_OV9282 = 121;
static constexpr int X_CAM_TYPE_ORQA_HORNET = 122;
static constexpr int X_CAM_TYPE_ORQA_JAGUAR = 123;
static constexpr int X_CAM_TYPE_ORQA_REKINDLE = 124;
static constexpr int X_CAM_TYPE_NXP_IMX8_V4L2 = 130;
static constexpr int X_CAM_TYPE_ROCKCHIP_RV110X = 140;
static constexpr int X_CAM_TYPE_DISABLED = 255;

struct CameraTypeNameEntry {
  int id;
  const char* name;
};

inline constexpr CameraTypeNameEntry kCameraTypeNameEntries[] = {
  {0, "DUMMY"},
  {2, "EXTERNAL"},
  {3, "EXTERNAL_IP"},
  {4, "DEV_FILESRC"},
  {10, "USB"},
  {11, "INFIRAY"},
  {12, "INFIRAY_T2"},
  {13, "INFIRAY_X2"},
  {14, "INFIRAY_P2_PRO"},
  {15, "FLIR VUE"},
  {16, "FLIR BOSON"},
  {20, "MMAL_HDMI"},
  {30, "RPIF_V1_OV5647"},
  {31, "RPIF_V2_IMX219"},
  {32, "RPIF_V3_IMX708"},
  {33, "RPIF_HQ_IMX477"},
  {40, "ARDUCAM_SKYMASTERHDR"},
  {41, "ARDUCAM_SKYVISIONPRO"},
  {42, "ARDUCAM_IMX477M"},
  {43, "ARDUCAM_IMX462"},
  {44, "ARDUCAM_IMX327"},
  {45, "ARDUCAM_IMX290"},
  {46, "ARDUCAM_IMX462_LOWLIGHT_MINI"},
  {47, "ARDUCAM_IMX662"},
  {48, "ARDUCAM_IMX415"},
  {60, "VEYE_2MP"},
  {61, "VEYE_IMX307"},
  {62, "VEYE_CSSC132"},
  {63, "VEYE_MVCAM"},
  {70, "X20_HDZERO_GENERIC"},
  {71, "X20_HDZERO_RUNCAM_V1"},
  {72, "X20_HDZERO_RUNCAM_V2"},
  {73, "X20_HDZERO_RUNCAM_V3"},
  {74, "X20_HDZERO_RUNCAM_NANO"},
  {75, "X20_OHD_Jaguar"},
  {76, "X21_OHD_Jaguar"},
  {77, "A733_IMX415"},
  {78, "A733_IMX219"},
  {79, "A733_IMX214"},
  {80, "ROCK_5_HDMI_IN"},
  {81, "ROCK_5_OV5647"},
  {82, "ROCK_5_IMX219"},
  {83, "ROCK_5_IMX708"},
  {84, "ROCK_5_IMX462"},
  {85, "ROCK_5_IMX415"},
  {86, "ROCK_5_IMX415"},
  {87, "ROCK_5_IMX415"},
  {88, "ROCK_5_OHD_Jaguar"},
  {90, "ROCK_3_HDMI_IN"},
  {91, "ROCK_3_OV5647"},
  {92, "ROCK_3_IMX219"},
  {93, "ROCK_3_IMX708"},
  {94, "ROCK_3_IMX462"},
  {95, "ROCK_3_IMX519"},
  {96, "ROCK_3_OHD_Jaguar"},
  {97, "ROCK_3_VEYE"},
  {101, "XAVIER_IMX577"},
  {110, "OPENIPC_X"},
  {120, "CORETRONIC IMX577"},
  {121, "CORETRONIC OV9282"},
  {122, "ORQA_HORNET"},
  {123, "ORQA_JAGUAR"},
  {124, "ORQA_REKINDLE"},
  {130, "NXP_IMX8_V4L2"},
  {140, "LUCKFOX_MIS5001"},
  {255, "DISABLED"},
};

inline std::string camera_type_to_string(int camera_type) {
  for (const auto& entry : kCameraTypeNameEntries) {
    if (entry.id == camera_type) {
      return entry.name;
    }
  }
  return "UNKNOWN (" + std::to_string(camera_type) + ")";
}

struct CameraUiEntry {
  int type;
  const char* label;
};

struct ResolutionEntry {
  int width_px;
  int height_px;
  int fps;
};

struct CameraResolutionEntry {
  int type;
  const ResolutionEntry* resolutions;
  std::size_t resolution_count;
};

struct ManufacturerEntry {
  const char* name;
  const CameraUiEntry* cameras;
  std::size_t camera_count;
};

struct PlatformCameraChoicesEntry {
  int platform_type;
  const ManufacturerEntry* manufacturers;
  std::size_t manufacturer_count;
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_DUMMY_SW[] = {
  {640, 480, 30},
  {1280, 720, 30},
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC[] = {
  {848, 480, 60},
  {1280, 720, 60},
  {1920, 1080, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_GENERIC[] = {
  {640, 480, 30},
  {0, 0, 0},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_INFIRAY[] = {
  {384, 292, 25},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2[] = {
  {256, 192, 25},
  {0, 0, 0},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2[] = {
  {384, 292, 50},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO[] = {
  {256, 192, 25},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE[] = {
  {640, 512, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON[] = {
  {640, 512, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI[] = {
  {1280, 720, 30},
  {1920, 1080, 25},
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647[] = {
  {1280, 720, 30},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219[] = {
  {640, 480, 47},
  {896, 504, 47},
  {1280, 720, 47},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708[] = {
  {640, 480, 60},
  {896, 504, 60},
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477[] = {
  {640, 480, 50},
  {896, 504, 50},
  {1280, 720, 50},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708[] = {
  {640, 480, 60},
  {896, 504, 60},
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519[] = {
  {640, 480, 60},
  {896, 504, 60},
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M[] = {
  {640, 480, 50},
  {896, 504, 50},
  {1280, 720, 50},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462[] = {
  {640, 480, 60},
  {896, 504, 30},
  {896, 504, 60},
  {1280, 720, 30},
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327[] = {
  {640, 480, 60},
  {896, 504, 60},
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI[] = {
  {640, 480, 60},
  {896, 504, 30},
  {896, 504, 60},
  {1280, 720, 30},
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
  {3840, 2160, 15},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP[] = {
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132[] = {
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM[] = {
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_A733_IMX415[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_A733_IMX219[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_A733_IMX214[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN[] = {
  {1280, 720, 30},
  {1280, 720, 60},
  {1920, 1080, 30},
  {1920, 1080, 60},
  {3840, 2160, 30},
  {3840, 2160, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647[] = {
  {640, 480, 60},
  {1280, 720, 30},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219[] = {
  {640, 480, 30},
  {848, 480, 30},
  {1280, 720, 30},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708[] = {
  {1280, 720, 30},
  {1280, 720, 60},
  {1920, 1080, 60},
  {4608, 2592, 14},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462[] = {
  {1280, 720, 30},
  {1280, 720, 60},
  {1920, 1080, 30},
  {1920, 1080, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415[] = {
  {1280, 720, 30},
  {1280, 720, 30},
  {1920, 1080, 30},
  {3864, 2192, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477[] = {
  {1280, 720, 60},
  {1920, 1080, 60},
  {3840, 2160, 20},
  {4056, 3040, 10},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519[] = {
  {1280, 720, 60},
  {1920, 1080, 60},
  {3840, 2160, 20},
  {4056, 3040, 9},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar[] = {
  {1280, 720, 120},
  {1920, 1080, 100},
  {3840, 2160, 90},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN[] = {
  {1280, 720, 30},
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647[] = {
  {640, 480, 60},
  {1280, 720, 30},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219[] = {
  {640, 480, 30},
  {848, 480, 30},
  {1280, 720, 30},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708[] = {
  {1280, 720, 30},
  {1280, 720, 60},
  {1920, 1080, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462[] = {
  {1280, 720, 60},
  {1280, 720, 30},
  {1920, 1080, 30},
  {1920, 1080, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519[] = {
  {1280, 720, 60},
  {1280, 720, 30},
  {1920, 1080, 30},
  {1920, 1080, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar[] = {
  {1280, 720, 60},
  {1280, 720, 120},
  {1920, 1080, 60},
  {1920, 1080, 100},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577[] = {
  {1280, 720, 60},
  {1920, 1080, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_QC_IMX577[] = {
  {1280, 720, 30},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_QC_OV9282[] = {
  {1280, 720, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ORQA_HORNET[] = {
  {960, 720, 120},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR[] = {
  {960, 720, 120},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE[] = {
  {1280, 720, 60},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2[] = {
  {1280, 720, 60},
  {1920, 1080, 30},
};

inline constexpr ResolutionEntry kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X[] = {
  {1296, 968, 60},
  {1920, 1080, 30},
  {1280, 720, 60},
};

inline constexpr CameraResolutionEntry kCameraResolutionEntries[] = {
  {X_CAM_TYPE_DUMMY_SW, kCameraResolutions_X_CAM_TYPE_DUMMY_SW, sizeof(kCameraResolutions_X_CAM_TYPE_DUMMY_SW) / sizeof(kCameraResolutions_X_CAM_TYPE_DUMMY_SW[0])},
  {X_CAM_TYPE_DEVELOPMENT_FILESRC, kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC, sizeof(kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC) / sizeof(kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC[0])},
  {X_CAM_TYPE_USB_GENERIC, kCameraResolutions_X_CAM_TYPE_USB_GENERIC, sizeof(kCameraResolutions_X_CAM_TYPE_USB_GENERIC) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_GENERIC[0])},
  {X_CAM_TYPE_USB_INFIRAY, kCameraResolutions_X_CAM_TYPE_USB_INFIRAY, sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY[0])},
  {X_CAM_TYPE_USB_INFIRAY_T2, kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2, sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2[0])},
  {X_CAM_TYPE_USB_INFIRAY_X2, kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2, sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2[0])},
  {X_CAM_TYPE_USB_INFIRAY_P2_PRO, kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO, sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO[0])},
  {X_CAM_TYPE_USB_FLIR_VUE, kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE, sizeof(kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE[0])},
  {X_CAM_TYPE_USB_FLIR_BOSON, kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON, sizeof(kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON) / sizeof(kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON[0])},
  {X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI, kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662[0])},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415, kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415[0])},
  {X_CAM_TYPE_RPI_V4L2_VEYE_2MP, kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP[0])},
  {X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307, kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307[0])},
  {X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132, kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132[0])},
  {X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM, kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM, sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM) / sizeof(kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM[0])},
  {X_CAM_TYPE_X20_HDZERO_GENERIC, kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC, sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC) / sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC[0])},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_V1, kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1, sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1) / sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1[0])},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_V2, kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2, sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2) / sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2[0])},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_V3, kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3, sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3) / sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3[0])},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90, kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90, sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90) / sizeof(kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90[0])},
  {X_CAM_TYPE_X20_OHD_Jaguar, kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar, sizeof(kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar) / sizeof(kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar[0])},
  {X_CAM_TYPE_X21_OHD_Jaguar, kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar, sizeof(kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar) / sizeof(kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar[0])},
  {X_CAM_TYPE_A733_IMX415, kCameraResolutions_X_CAM_TYPE_A733_IMX415, sizeof(kCameraResolutions_X_CAM_TYPE_A733_IMX415) / sizeof(kCameraResolutions_X_CAM_TYPE_A733_IMX415[0])},
  {X_CAM_TYPE_A733_IMX219, kCameraResolutions_X_CAM_TYPE_A733_IMX219, sizeof(kCameraResolutions_X_CAM_TYPE_A733_IMX219) / sizeof(kCameraResolutions_X_CAM_TYPE_A733_IMX219[0])},
  {X_CAM_TYPE_A733_IMX214, kCameraResolutions_X_CAM_TYPE_A733_IMX214, sizeof(kCameraResolutions_X_CAM_TYPE_A733_IMX214) / sizeof(kCameraResolutions_X_CAM_TYPE_A733_IMX214[0])},
  {X_CAM_TYPE_ROCK_5_HDMI_IN, kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN[0])},
  {X_CAM_TYPE_ROCK_5_OV5647, kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647[0])},
  {X_CAM_TYPE_ROCK_5_IMX219, kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219[0])},
  {X_CAM_TYPE_ROCK_5_IMX708, kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708[0])},
  {X_CAM_TYPE_ROCK_5_IMX462, kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462[0])},
  {X_CAM_TYPE_ROCK_5_IMX415, kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415[0])},
  {X_CAM_TYPE_ROCK_5_IMX477, kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477[0])},
  {X_CAM_TYPE_ROCK_5_IMX519, kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519[0])},
  {X_CAM_TYPE_ROCK_5_OHD_Jaguar, kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar[0])},
  {X_CAM_TYPE_ROCK_3_HDMI_IN, kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN[0])},
  {X_CAM_TYPE_ROCK_3_OV5647, kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647[0])},
  {X_CAM_TYPE_ROCK_3_IMX219, kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219[0])},
  {X_CAM_TYPE_ROCK_3_IMX708, kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708[0])},
  {X_CAM_TYPE_ROCK_3_IMX462, kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462[0])},
  {X_CAM_TYPE_ROCK_3_IMX519, kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519[0])},
  {X_CAM_TYPE_ROCK_3_OHD_Jaguar, kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar, sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar[0])},
  {X_CAM_TYPE_NVIDIA_XAVIER_IMX577, kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577, sizeof(kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577) / sizeof(kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577[0])},
  {X_CAM_TYPE_QC_IMX577, kCameraResolutions_X_CAM_TYPE_QC_IMX577, sizeof(kCameraResolutions_X_CAM_TYPE_QC_IMX577) / sizeof(kCameraResolutions_X_CAM_TYPE_QC_IMX577[0])},
  {X_CAM_TYPE_QC_OV9282, kCameraResolutions_X_CAM_TYPE_QC_OV9282, sizeof(kCameraResolutions_X_CAM_TYPE_QC_OV9282) / sizeof(kCameraResolutions_X_CAM_TYPE_QC_OV9282[0])},
  {X_CAM_TYPE_ORQA_HORNET, kCameraResolutions_X_CAM_TYPE_ORQA_HORNET, sizeof(kCameraResolutions_X_CAM_TYPE_ORQA_HORNET) / sizeof(kCameraResolutions_X_CAM_TYPE_ORQA_HORNET[0])},
  {X_CAM_TYPE_ORQA_JAGUAR, kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR, sizeof(kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR) / sizeof(kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR[0])},
  {X_CAM_TYPE_ORQA_REKINDLE, kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE, sizeof(kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE) / sizeof(kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE[0])},
  {X_CAM_TYPE_NXP_IMX8_V4L2, kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2, sizeof(kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2) / sizeof(kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2[0])},
  {X_CAM_TYPE_ROCKCHIP_RV110X, kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X, sizeof(kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X) / sizeof(kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X[0])},
};

inline const CameraResolutionEntry* find_camera_resolutions(int camera_type) {
  for (const auto& entry : kCameraResolutionEntries) {
    if (entry.type == camera_type) {
      return &entry;
    }
  }
  return nullptr;
}

inline constexpr CameraUiEntry kManufacturer_USB_Cameras[] = {
  {X_CAM_TYPE_USB_INFIRAY, "INFIRAY USB"},
  {X_CAM_TYPE_USB_INFIRAY_T2, "INFIRAY USB T2"},
  {X_CAM_TYPE_USB_INFIRAY_P2_PRO, "INFIRAY USB P2 Pro"},
  {X_CAM_TYPE_USB_INFIRAY_X2, "INFIRAY USB X2"},
  {X_CAM_TYPE_USB_FLIR_VUE, "FLIR_VUE"},
  {X_CAM_TYPE_USB_FLIR_BOSON, "FLIR_BOSON"},
  {X_CAM_TYPE_USB_GENERIC, "EXP USB GENERIC"},
};

inline constexpr ManufacturerEntry kManufacturer_USB = {"USB", kManufacturer_USB_Cameras, sizeof(kManufacturer_USB_Cameras) / sizeof(kManufacturer_USB_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_DEBUG_Cameras[] = {
  {X_CAM_TYPE_DUMMY_SW, "Dummy (debug)"},
  {X_CAM_TYPE_EXTERNAL, "External (DEV)"},
  {X_CAM_TYPE_DEVELOPMENT_FILESRC, "DEV Filecamera"},
};

inline constexpr ManufacturerEntry kManufacturer_DEBUG = {"DEV/DEBUG", kManufacturer_DEBUG_Cameras, sizeof(kManufacturer_DEBUG_Cameras) / sizeof(kManufacturer_DEBUG_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_DISABLE_Cameras[] = {
  {X_CAM_TYPE_DISABLED, "DISABLE"},
};

inline constexpr ManufacturerEntry kManufacturer_DISABLE = {"DISABLE", kManufacturer_DISABLE_Cameras, sizeof(kManufacturer_DISABLE_Cameras) / sizeof(kManufacturer_DISABLE_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_RPI_ARDUCAM_Cameras[] = {
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708, "SKYMASTERHDR"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519, "SKYVISIONPRO"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M, "IMX477m"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462, "IMX462"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327, "IMX327"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX290, "IMX290"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI, "IMX462_LOWLIGHT_MINI"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662, "IMX662"},
  {X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415, "IMX415 4K"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_ARDUCAM = {"ARDUCAM", kManufacturer_RPI_ARDUCAM_Cameras, sizeof(kManufacturer_RPI_ARDUCAM_Cameras) / sizeof(kManufacturer_RPI_ARDUCAM_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_RPI_VEYE_Cameras[] = {
  {X_CAM_TYPE_RPI_V4L2_VEYE_2MP, "2MP"},
  {X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307, "CSIMX307"},
  {X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132, "CSSC132"},
  {X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM, "MVCAM"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_VEYE = {"VEYE", kManufacturer_RPI_VEYE_Cameras, sizeof(kManufacturer_RPI_VEYE_Cameras) / sizeof(kManufacturer_RPI_VEYE_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_RPI_RPIF_Cameras[] = {
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647, "V1 OV5647"},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219, "V2 IMX219"},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708, "V3 IMX708"},
  {X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477, "HQ IMX477"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_RPIF = {"RPI FOUNDATION", kManufacturer_RPI_RPIF_Cameras, sizeof(kManufacturer_RPI_RPIF_Cameras) / sizeof(kManufacturer_RPI_RPIF_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_RPI_HDMI_Cameras[] = {
  {X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI, "GENERIC HDMI to CSI"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_HDMI = {"HDMI TO CSI", kManufacturer_RPI_HDMI_Cameras, sizeof(kManufacturer_RPI_HDMI_Cameras) / sizeof(kManufacturer_RPI_HDMI_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_X20_HDZERO_Cameras[] = {
  {X_CAM_TYPE_X20_HDZERO_GENERIC, "GENERIC"},
};

inline constexpr ManufacturerEntry kManufacturer_X20_HDZERO = {"HDZERO", kManufacturer_X20_HDZERO_Cameras, sizeof(kManufacturer_X20_HDZERO_Cameras) / sizeof(kManufacturer_X20_HDZERO_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_X20_RUNCAM_Cameras[] = {
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_V1, "RUNCAM V1"},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_V2, "RUNCAM V2"},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_V3, "RUNCAM V3"},
  {X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90, "RUNCAM NANO 90"},
  {X_CAM_TYPE_X20_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_X20_RUNCAM = {"RUNCAM", kManufacturer_X20_RUNCAM_Cameras, sizeof(kManufacturer_X20_RUNCAM_Cameras) / sizeof(kManufacturer_X20_RUNCAM_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_A733_ALLWINNER_Cameras[] = {
  {X_CAM_TYPE_A733_IMX415, "IMX415"},
  {X_CAM_TYPE_A733_IMX219, "IMX219"},
  {X_CAM_TYPE_A733_IMX214, "IMX214"},
};

inline constexpr ManufacturerEntry kManufacturer_A733_ALLWINNER = {"ALLWINNER", kManufacturer_A733_ALLWINNER_Cameras, sizeof(kManufacturer_A733_ALLWINNER_Cameras) / sizeof(kManufacturer_A733_ALLWINNER_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_ROCK3_ARDUCAM_Cameras[] = {
  {X_CAM_TYPE_ROCK_3_IMX462, "IMX462"},
  {X_CAM_TYPE_ROCK_3_IMX519, "IMX519"},
  {X_CAM_TYPE_ROCK_3_IMX708, "IMX708"},
  {X_CAM_TYPE_ROCK_3_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_ROCK3_ARDUCAM = {"Arducam", kManufacturer_ROCK3_ARDUCAM_Cameras, sizeof(kManufacturer_ROCK3_ARDUCAM_Cameras) / sizeof(kManufacturer_ROCK3_ARDUCAM_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_ROCK5_A_GENERIC_Cameras[] = {
  {X_CAM_TYPE_ROCK_5_IMX415, "IMX415"},
  {X_CAM_TYPE_ROCK_5_IMX462, "IMX462"},
  {X_CAM_TYPE_ROCK_5_IMX477, "IMX477"},
  {X_CAM_TYPE_ROCK_5_IMX519, "IMX519"},
  {X_CAM_TYPE_ROCK_5_OV5647, "OV5647"},
  {X_CAM_TYPE_ROCK_5_IMX219, "IMX219"},
  {X_CAM_TYPE_ROCK_5_IMX708, "IMX708"},
  {X_CAM_TYPE_ROCK_5_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_ROCK5_A_GENERIC = {"Generic", kManufacturer_ROCK5_A_GENERIC_Cameras, sizeof(kManufacturer_ROCK5_A_GENERIC_Cameras) / sizeof(kManufacturer_ROCK5_A_GENERIC_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_ROCK5_B_GENERIC_Cameras[] = {
  {X_CAM_TYPE_ROCK_5_HDMI_IN, "HDMI IN"},
  {X_CAM_TYPE_ROCK_5_IMX415, "IMX415"},
  {X_CAM_TYPE_ROCK_5_IMX462, "IMX462"},
  {X_CAM_TYPE_ROCK_5_IMX477, "IMX477"},
  {X_CAM_TYPE_ROCK_5_IMX519, "IMX519"},
  {X_CAM_TYPE_ROCK_5_OV5647, "OV5647"},
  {X_CAM_TYPE_ROCK_5_IMX219, "IMX219"},
  {X_CAM_TYPE_ROCK_5_IMX708, "IMX708"},
  {X_CAM_TYPE_ROCK_5_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_ROCK5_B_GENERIC = {"Generic", kManufacturer_ROCK5_B_GENERIC_Cameras, sizeof(kManufacturer_ROCK5_B_GENERIC_Cameras) / sizeof(kManufacturer_ROCK5_B_GENERIC_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_NVIDIA_LEOPARD_Cameras[] = {
  {X_CAM_TYPE_NVIDIA_XAVIER_IMX577, "IMX577"},
};

inline constexpr ManufacturerEntry kManufacturer_NVIDIA_LEOPARD = {"LEOPARD", kManufacturer_NVIDIA_LEOPARD_Cameras, sizeof(kManufacturer_NVIDIA_LEOPARD_Cameras) / sizeof(kManufacturer_NVIDIA_LEOPARD_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_ORQA_Cameras[] = {
  {X_CAM_TYPE_ORQA_HORNET, "HORNET"},
  {X_CAM_TYPE_ORQA_JAGUAR, "JAGUAR"},
  {X_CAM_TYPE_ORQA_REKINDLE, "REKINDLE"},
};

inline constexpr ManufacturerEntry kManufacturer_ORQA = {"ORQA", kManufacturer_ORQA_Cameras, sizeof(kManufacturer_ORQA_Cameras) / sizeof(kManufacturer_ORQA_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_NXP_Cameras[] = {
  {X_CAM_TYPE_NXP_IMX8_V4L2, "V4L2 CSI"},
};

inline constexpr ManufacturerEntry kManufacturer_NXP = {"NXP", kManufacturer_NXP_Cameras, sizeof(kManufacturer_NXP_Cameras) / sizeof(kManufacturer_NXP_Cameras[0])};

inline constexpr CameraUiEntry kManufacturer_LUCKFOX_Cameras[] = {
  {X_CAM_TYPE_ROCKCHIP_RV110X, "MIS5001"},
};

inline constexpr ManufacturerEntry kManufacturer_LUCKFOX = {"LUCKFOX", kManufacturer_LUCKFOX_Cameras, sizeof(kManufacturer_LUCKFOX_Cameras) / sizeof(kManufacturer_LUCKFOX_Cameras[0])};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers[] = {
  kManufacturer_RPI_ARDUCAM,
  kManufacturer_RPI_VEYE,
  kManufacturer_RPI_RPIF,
  kManufacturer_RPI_HDMI,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers[] = {
  kManufacturer_RPI_ARDUCAM,
  kManufacturer_RPI_VEYE,
  kManufacturer_RPI_RPIF,
  kManufacturer_RPI_HDMI,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers[] = {
  kManufacturer_RPI_ARDUCAM,
  kManufacturer_RPI_VEYE,
  kManufacturer_RPI_RPIF,
  kManufacturer_RPI_HDMI,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers[] = {
  kManufacturer_X20_HDZERO,
  kManufacturer_X20_RUNCAM,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers[] = {
  kManufacturer_A733_ALLWINNER,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers[] = {
  kManufacturer_ROCK3_ARDUCAM,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers[] = {
  kManufacturer_ROCK3_ARDUCAM,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers[] = {
  kManufacturer_ROCK5_A_GENERIC,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers[] = {
  kManufacturer_ROCK5_B_GENERIC,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_X86_Manufacturers[] = {
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers[] = {
  kManufacturer_NVIDIA_LEOPARD,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers[] = {
  kManufacturer_ORQA,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers[] = {
  kManufacturer_NXP,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr ManufacturerEntry kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers[] = {
  kManufacturer_LUCKFOX,
};

inline constexpr PlatformCameraChoicesEntry kPlatformCameraChoices[] = {
  {X_PLATFORM_TYPE_RPI_OLD, kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers[0])},
  {X_PLATFORM_TYPE_RPI_4, kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers[0])},
  {X_PLATFORM_TYPE_RPI_CM4, kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers[0])},
  {X_PLATFORM_TYPE_ALWINNER_X20, kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers[0])},
  {X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z, kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers[0])},
  {X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W, kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers[0])},
  {X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3, kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers[0])},
  {X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A, kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers[0])},
  {X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B, kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers[0])},
  {X_PLATFORM_TYPE_X86, kPlatform_X_PLATFORM_TYPE_X86_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_X86_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_X86_Manufacturers[0])},
  {X_PLATFORM_TYPE_NVIDIA_XAVIER, kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers[0])},
  {X_PLATFORM_TYPE_ORQA, kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers[0])},
  {X_PLATFORM_TYPE_NXP_IMX8, kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers[0])},
  {X_PLATFORM_TYPE_LUCKFOX_RV110X, kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers, sizeof(kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers) / sizeof(kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers[0])},
};

inline constexpr ManufacturerEntry kSecondaryManufacturers[] = {
  kManufacturer_DISABLE,
  kManufacturer_USB,
  kManufacturer_DEBUG,
};

inline constexpr std::size_t kSecondaryManufacturerCount = sizeof(kSecondaryManufacturers) / sizeof(kSecondaryManufacturers[0]);

inline constexpr ManufacturerEntry kFallbackManufacturers[] = {
  kManufacturer_DEBUG,
};

inline constexpr std::size_t kFallbackManufacturerCount = sizeof(kFallbackManufacturers) / sizeof(kFallbackManufacturers[0]);

inline const PlatformCameraChoicesEntry* find_platform_camera_choices(int platform_type) {
  for (const auto& entry : kPlatformCameraChoices) {
    if (entry.platform_type == platform_type) {
      return &entry;
    }
  }
  return nullptr;
}

}  // namespace camera_registry
}  // namespace openhd

using openhd::camera_registry::X_CAM_TYPE_DUMMY_SW;
using openhd::camera_registry::X_CAM_TYPE_EXTERNAL;
using openhd::camera_registry::X_CAM_TYPE_EXTERNAL_IP;
using openhd::camera_registry::X_CAM_TYPE_DEVELOPMENT_FILESRC;
using openhd::camera_registry::X_CAM_TYPE_USB_GENERIC;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY_T2;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY_X2;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY_P2_PRO;
using openhd::camera_registry::X_CAM_TYPE_USB_FLIR_VUE;
using openhd::camera_registry::X_CAM_TYPE_USB_FLIR_BOSON;
using openhd::camera_registry::X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX290;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_2MP;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_GENERIC;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_V1;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_V2;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_V3;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90;
using openhd::camera_registry::X_CAM_TYPE_X20_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_X21_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_A733_IMX415;
using openhd::camera_registry::X_CAM_TYPE_A733_IMX219;
using openhd::camera_registry::X_CAM_TYPE_A733_IMX214;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_HDMI_IN;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_OV5647;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX219;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX708;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX462;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX415;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX477;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX519;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_HDMI_IN;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_OV5647;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX219;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX708;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX462;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX519;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_VEYE;
using openhd::camera_registry::X_CAM_TYPE_NVIDIA_XAVIER_IMX577;
using openhd::camera_registry::X_CAM_TYPE_OPENIPC_GENERIC;
using openhd::camera_registry::X_CAM_TYPE_QC_IMX577;
using openhd::camera_registry::X_CAM_TYPE_QC_OV9282;
using openhd::camera_registry::X_CAM_TYPE_ORQA_HORNET;
using openhd::camera_registry::X_CAM_TYPE_ORQA_JAGUAR;
using openhd::camera_registry::X_CAM_TYPE_ORQA_REKINDLE;
using openhd::camera_registry::X_CAM_TYPE_NXP_IMX8_V4L2;
using openhd::camera_registry::X_CAM_TYPE_ROCKCHIP_RV110X;
using openhd::camera_registry::X_CAM_TYPE_DISABLED;
