// Generated by tools/gen_camera_registry.py. Do not edit by hand.
#pragma once

#include <array>
#include <cstddef>
#include <string>

#include "openhd_platform.h"

namespace openhd::camera_registry {

static constexpr int X_CAM_TYPE_DUMMY_SW = 0;
static constexpr int X_CAM_TYPE_EXTERNAL = 2;
static constexpr int X_CAM_TYPE_EXTERNAL_IP = 3;
static constexpr int X_CAM_TYPE_DEVELOPMENT_FILESRC = 4;
static constexpr int X_CAM_TYPE_USB_GENERIC = 10;
static constexpr int X_CAM_TYPE_USB_INFIRAY = 11;
static constexpr int X_CAM_TYPE_USB_INFIRAY_T2 = 12;
static constexpr int X_CAM_TYPE_USB_INFIRAY_X2 = 13;
static constexpr int X_CAM_TYPE_USB_INFIRAY_P2_PRO = 14;
static constexpr int X_CAM_TYPE_USB_FLIR_VUE = 15;
static constexpr int X_CAM_TYPE_USB_FLIR_BOSON = 16;
static constexpr int X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI = 20;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647 = 30;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219 = 31;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708 = 32;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477 = 33;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708 = 40;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519 = 41;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M = 42;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462 = 43;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327 = 44;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX290 = 45;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI = 46;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662 = 47;
static constexpr int X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415 = 48;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_2MP = 60;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307 = 61;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132 = 62;
static constexpr int X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM = 63;
static constexpr int X_CAM_TYPE_X20_HDZERO_GENERIC = 70;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_V1 = 71;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_V2 = 72;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_V3 = 73;
static constexpr int X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90 = 74;
static constexpr int X_CAM_TYPE_X20_OHD_Jaguar = 75;
static constexpr int X_CAM_TYPE_X21_OHD_Jaguar = 76;
static constexpr int X_CAM_TYPE_A733_IMX415 = 77;
static constexpr int X_CAM_TYPE_A733_IMX219 = 78;
static constexpr int X_CAM_TYPE_A733_IMX214 = 79;
static constexpr int X_CAM_TYPE_ROCK_5_HDMI_IN = 80;
static constexpr int X_CAM_TYPE_ROCK_5_OV5647 = 81;
static constexpr int X_CAM_TYPE_ROCK_5_IMX219 = 82;
static constexpr int X_CAM_TYPE_ROCK_5_IMX708 = 83;
static constexpr int X_CAM_TYPE_ROCK_5_IMX462 = 84;
static constexpr int X_CAM_TYPE_ROCK_5_IMX415 = 85;
static constexpr int X_CAM_TYPE_ROCK_5_IMX477 = 86;
static constexpr int X_CAM_TYPE_ROCK_5_IMX519 = 87;
static constexpr int X_CAM_TYPE_ROCK_5_OHD_Jaguar = 88;
static constexpr int X_CAM_TYPE_ROCK_3_HDMI_IN = 90;
static constexpr int X_CAM_TYPE_ROCK_3_OV5647 = 91;
static constexpr int X_CAM_TYPE_ROCK_3_IMX219 = 92;
static constexpr int X_CAM_TYPE_ROCK_3_IMX708 = 93;
static constexpr int X_CAM_TYPE_ROCK_3_IMX462 = 94;
static constexpr int X_CAM_TYPE_ROCK_3_IMX519 = 95;
static constexpr int X_CAM_TYPE_ROCK_3_OHD_Jaguar = 96;
static constexpr int X_CAM_TYPE_ROCK_3_VEYE = 97;
static constexpr int X_CAM_TYPE_NVIDIA_XAVIER_IMX577 = 101;
static constexpr int X_CAM_TYPE_OPENIPC_GENERIC = 110;
static constexpr int X_CAM_TYPE_QC_IMX577 = 120;
static constexpr int X_CAM_TYPE_QC_OV9282 = 121;
static constexpr int X_CAM_TYPE_ORQA_HORNET = 122;
static constexpr int X_CAM_TYPE_ORQA_JAGUAR = 123;
static constexpr int X_CAM_TYPE_ORQA_REKINDLE = 124;
static constexpr int X_CAM_TYPE_NXP_IMX8_V4L2 = 130;
static constexpr int X_CAM_TYPE_ROCKCHIP_RV110X = 140;
static constexpr int X_CAM_TYPE_DISABLED = 255;

struct CameraTypeNameEntry {
  int id;
  const char* name;
};

inline constexpr std::array kCameraTypeNameEntries = {
    CameraTypeNameEntry{0, "DUMMY"},
    CameraTypeNameEntry{2, "EXTERNAL"},
    CameraTypeNameEntry{3, "EXTERNAL_IP"},
    CameraTypeNameEntry{4, "DEV_FILESRC"},
    CameraTypeNameEntry{10, "USB"},
    CameraTypeNameEntry{11, "INFIRAY"},
    CameraTypeNameEntry{12, "INFIRAY_T2"},
    CameraTypeNameEntry{13, "INFIRAY_X2"},
    CameraTypeNameEntry{14, "INFIRAY_P2_PRO"},
    CameraTypeNameEntry{15, "FLIR VUE"},
    CameraTypeNameEntry{16, "FLIR BOSON"},
    CameraTypeNameEntry{20, "MMAL_HDMI"},
    CameraTypeNameEntry{30, "RPIF_V1_OV5647"},
    CameraTypeNameEntry{31, "RPIF_V2_IMX219"},
    CameraTypeNameEntry{32, "RPIF_V3_IMX708"},
    CameraTypeNameEntry{33, "RPIF_HQ_IMX477"},
    CameraTypeNameEntry{40, "ARDUCAM_SKYMASTERHDR"},
    CameraTypeNameEntry{41, "ARDUCAM_SKYVISIONPRO"},
    CameraTypeNameEntry{42, "ARDUCAM_IMX477M"},
    CameraTypeNameEntry{43, "ARDUCAM_IMX462"},
    CameraTypeNameEntry{44, "ARDUCAM_IMX327"},
    CameraTypeNameEntry{45, "ARDUCAM_IMX290"},
    CameraTypeNameEntry{46, "ARDUCAM_IMX462_LOWLIGHT_MINI"},
    CameraTypeNameEntry{47, "ARDUCAM_IMX662"},
    CameraTypeNameEntry{48, "ARDUCAM_IMX415"},
    CameraTypeNameEntry{60, "VEYE_2MP"},
    CameraTypeNameEntry{61, "VEYE_IMX307"},
    CameraTypeNameEntry{62, "VEYE_CSSC132"},
    CameraTypeNameEntry{63, "VEYE_MVCAM"},
    CameraTypeNameEntry{70, "X20_HDZERO_GENERIC"},
    CameraTypeNameEntry{71, "X20_HDZERO_RUNCAM_V1"},
    CameraTypeNameEntry{72, "X20_HDZERO_RUNCAM_V2"},
    CameraTypeNameEntry{73, "X20_HDZERO_RUNCAM_V3"},
    CameraTypeNameEntry{74, "X20_HDZERO_RUNCAM_NANO"},
    CameraTypeNameEntry{75, "X20_OHD_Jaguar"},
    CameraTypeNameEntry{76, "X21_OHD_Jaguar"},
    CameraTypeNameEntry{77, "A733_IMX415"},
    CameraTypeNameEntry{78, "A733_IMX219"},
    CameraTypeNameEntry{79, "A733_IMX214"},
    CameraTypeNameEntry{80, "ROCK_5_HDMI_IN"},
    CameraTypeNameEntry{81, "ROCK_5_OV5647"},
    CameraTypeNameEntry{82, "ROCK_5_IMX219"},
    CameraTypeNameEntry{83, "ROCK_5_IMX708"},
    CameraTypeNameEntry{84, "ROCK_5_IMX462"},
    CameraTypeNameEntry{85, "ROCK_5_IMX415"},
    CameraTypeNameEntry{86, "ROCK_5_IMX415"},
    CameraTypeNameEntry{87, "ROCK_5_IMX415"},
    CameraTypeNameEntry{88, "ROCK_5_OHD_Jaguar"},
    CameraTypeNameEntry{90, "ROCK_3_HDMI_IN"},
    CameraTypeNameEntry{91, "ROCK_3_OV5647"},
    CameraTypeNameEntry{92, "ROCK_3_IMX219"},
    CameraTypeNameEntry{93, "ROCK_3_IMX708"},
    CameraTypeNameEntry{94, "ROCK_3_IMX462"},
    CameraTypeNameEntry{95, "ROCK_3_IMX519"},
    CameraTypeNameEntry{96, "ROCK_3_OHD_Jaguar"},
    CameraTypeNameEntry{97, "ROCK_3_VEYE"},
    CameraTypeNameEntry{101, "XAVIER_IMX577"},
    CameraTypeNameEntry{110, "OPENIPC_X"},
    CameraTypeNameEntry{120, "CORETRONIC IMX577"},
    CameraTypeNameEntry{121, "CORETRONIC OV9282"},
    CameraTypeNameEntry{122, "ORQA_HORNET"},
    CameraTypeNameEntry{123, "ORQA_JAGUAR"},
    CameraTypeNameEntry{124, "ORQA_REKINDLE"},
    CameraTypeNameEntry{130, "NXP_IMX8_V4L2"},
    CameraTypeNameEntry{140, "LUCKFOX_MIS5001"},
    CameraTypeNameEntry{255, "DISABLED"},
};

inline std::string camera_type_to_string(int camera_type) {
  for (const auto& entry : kCameraTypeNameEntries) {
    if (entry.id == camera_type) {
      return entry.name;
    }
  }
  return std::string{"UNKNOWN ("} + std::to_string(camera_type) +
         ")";  // NOSONAR
}

struct CameraUiEntry {
  int type;
  const char* label;
};

struct ResolutionEntry {
  int width_px;
  int height_px;
  int fps;
};

struct CameraResolutionEntry {
  int type;
  const ResolutionEntry* resolutions;
  std::size_t resolution_count;
};

struct ManufacturerEntry {
  const char* name;
  const CameraUiEntry* cameras;
  std::size_t camera_count;
};

struct PlatformCameraChoicesEntry {
  int platform_type;
  const ManufacturerEntry* manufacturers;
  std::size_t manufacturer_count;
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_DUMMY_SW = {
    ResolutionEntry{640, 480, 30},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC =
    {
        ResolutionEntry{848, 480, 60},
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_GENERIC = {
    ResolutionEntry{640, 480, 30},
    ResolutionEntry{0, 0, 0},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_INFIRAY = {
    ResolutionEntry{384, 292, 25},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2 = {
    ResolutionEntry{256, 192, 25},
    ResolutionEntry{0, 0, 0},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2 = {
    ResolutionEntry{384, 292, 50},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO = {
    ResolutionEntry{256, 192, 25},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE = {
    ResolutionEntry{640, 512, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON = {
    ResolutionEntry{640, 512, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI =
    {
        ResolutionEntry{1280, 720, 30},
        ResolutionEntry{1920, 1080, 25},
        ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647 = {
        ResolutionEntry{1280, 720, 30},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219 = {
        ResolutionEntry{640, 480, 47},
        ResolutionEntry{896, 504, 47},
        ResolutionEntry{1280, 720, 47},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708 = {
        ResolutionEntry{640, 480, 60},
        ResolutionEntry{896, 504, 60},
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477 = {
        ResolutionEntry{640, 480, 50},
        ResolutionEntry{896, 504, 50},
        ResolutionEntry{1280, 720, 50},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708 = {
        ResolutionEntry{640, 480, 60},
        ResolutionEntry{896, 504, 60},
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519 = {
        ResolutionEntry{640, 480, 60},
        ResolutionEntry{896, 504, 60},
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M = {
        ResolutionEntry{640, 480, 50},
        ResolutionEntry{896, 504, 50},
        ResolutionEntry{1280, 720, 50},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462 = {
        ResolutionEntry{640, 480, 60},  ResolutionEntry{896, 504, 30},
        ResolutionEntry{896, 504, 60},  ResolutionEntry{1280, 720, 30},
        ResolutionEntry{1280, 720, 60}, ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327 = {
        ResolutionEntry{640, 480, 60},
        ResolutionEntry{896, 504, 60},
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI = {
        ResolutionEntry{640, 480, 60},  ResolutionEntry{896, 504, 30},
        ResolutionEntry{896, 504, 60},  ResolutionEntry{1280, 720, 30},
        ResolutionEntry{1280, 720, 60}, ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662 = {
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415 = {
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
        ResolutionEntry{3840, 2160, 15},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP = {
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307 = {
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132 = {
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM =
    {
        ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC = {
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1 =
    {
        ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2 =
    {
        ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3 =
    {
        ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array
    kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90 = {
        ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar = {
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar = {
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_A733_IMX415 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_A733_IMX219 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_A733_IMX214 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN = {
    ResolutionEntry{1280, 720, 30},  ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 30}, ResolutionEntry{1920, 1080, 60},
    ResolutionEntry{3840, 2160, 30}, ResolutionEntry{3840, 2160, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647 = {
    ResolutionEntry{640, 480, 60},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219 = {
    ResolutionEntry{640, 480, 30},
    ResolutionEntry{848, 480, 30},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708 = {
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 60},
    ResolutionEntry{4608, 2592, 14},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462 = {
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 30},
    ResolutionEntry{1920, 1080, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415 = {
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
    ResolutionEntry{3864, 2192, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 60},
    ResolutionEntry{3840, 2160, 20},
    ResolutionEntry{4056, 3040, 10},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 60},
    ResolutionEntry{3840, 2160, 20},
    ResolutionEntry{4056, 3040, 9},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar = {
    ResolutionEntry{1280, 720, 120},
    ResolutionEntry{1920, 1080, 100},
    ResolutionEntry{3840, 2160, 90},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN = {
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647 = {
    ResolutionEntry{640, 480, 60},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219 = {
    ResolutionEntry{640, 480, 30},
    ResolutionEntry{848, 480, 30},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708 = {
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
    ResolutionEntry{1920, 1080, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
    ResolutionEntry{1920, 1080, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1280, 720, 120},
    ResolutionEntry{1920, 1080, 60},
    ResolutionEntry{1920, 1080, 100},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577 =
    {
        ResolutionEntry{1280, 720, 60},
        ResolutionEntry{1920, 1080, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_QC_IMX577 = {
    ResolutionEntry{1280, 720, 30},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_QC_OV9282 = {
    ResolutionEntry{1280, 720, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ORQA_HORNET = {
    ResolutionEntry{960, 720, 120},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR = {
    ResolutionEntry{960, 720, 120},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE = {
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2 = {
    ResolutionEntry{1280, 720, 60},
    ResolutionEntry{1920, 1080, 30},
};

inline constexpr std::array kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X = {
    ResolutionEntry{1296, 968, 60},
    ResolutionEntry{1920, 1080, 30},
    ResolutionEntry{1280, 720, 60},
};

inline constexpr std::array kCameraResolutionEntries = {
    CameraResolutionEntry{X_CAM_TYPE_DUMMY_SW,
                          kCameraResolutions_X_CAM_TYPE_DUMMY_SW.data(),
                          kCameraResolutions_X_CAM_TYPE_DUMMY_SW.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_DEVELOPMENT_FILESRC,
        kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC.data(),
        kCameraResolutions_X_CAM_TYPE_DEVELOPMENT_FILESRC.size()},
    CameraResolutionEntry{X_CAM_TYPE_USB_GENERIC,
                          kCameraResolutions_X_CAM_TYPE_USB_GENERIC.data(),
                          kCameraResolutions_X_CAM_TYPE_USB_GENERIC.size()},
    CameraResolutionEntry{X_CAM_TYPE_USB_INFIRAY,
                          kCameraResolutions_X_CAM_TYPE_USB_INFIRAY.data(),
                          kCameraResolutions_X_CAM_TYPE_USB_INFIRAY.size()},
    CameraResolutionEntry{X_CAM_TYPE_USB_INFIRAY_T2,
                          kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2.data(),
                          kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_T2.size()},
    CameraResolutionEntry{X_CAM_TYPE_USB_INFIRAY_X2,
                          kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2.data(),
                          kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_X2.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_USB_INFIRAY_P2_PRO,
        kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO.data(),
        kCameraResolutions_X_CAM_TYPE_USB_INFIRAY_P2_PRO.size()},
    CameraResolutionEntry{X_CAM_TYPE_USB_FLIR_VUE,
                          kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE.data(),
                          kCameraResolutions_X_CAM_TYPE_USB_FLIR_VUE.size()},
    CameraResolutionEntry{X_CAM_TYPE_USB_FLIR_BOSON,
                          kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON.data(),
                          kCameraResolutions_X_CAM_TYPE_USB_FLIR_BOSON.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI,
        kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708
            .data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708
            .size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519
            .data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519
            .size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI
            .data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI
            .size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415,
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_V4L2_VEYE_2MP,
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_2MP.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307,
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132,
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM,
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM.data(),
        kCameraResolutions_X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_X20_HDZERO_GENERIC,
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC.data(),
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_GENERIC.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_X20_HDZERO_RUNCAM_V1,
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1.data(),
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V1.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_X20_HDZERO_RUNCAM_V2,
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2.data(),
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V2.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_X20_HDZERO_RUNCAM_V3,
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3.data(),
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_V3.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90,
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90.data(),
        kCameraResolutions_X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90.size()},
    CameraResolutionEntry{X_CAM_TYPE_X20_OHD_Jaguar,
                          kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar.data(),
                          kCameraResolutions_X_CAM_TYPE_X20_OHD_Jaguar.size()},
    CameraResolutionEntry{X_CAM_TYPE_X21_OHD_Jaguar,
                          kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar.data(),
                          kCameraResolutions_X_CAM_TYPE_X21_OHD_Jaguar.size()},
    CameraResolutionEntry{X_CAM_TYPE_A733_IMX415,
                          kCameraResolutions_X_CAM_TYPE_A733_IMX415.data(),
                          kCameraResolutions_X_CAM_TYPE_A733_IMX415.size()},
    CameraResolutionEntry{X_CAM_TYPE_A733_IMX219,
                          kCameraResolutions_X_CAM_TYPE_A733_IMX219.data(),
                          kCameraResolutions_X_CAM_TYPE_A733_IMX219.size()},
    CameraResolutionEntry{X_CAM_TYPE_A733_IMX214,
                          kCameraResolutions_X_CAM_TYPE_A733_IMX214.data(),
                          kCameraResolutions_X_CAM_TYPE_A733_IMX214.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_HDMI_IN,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_HDMI_IN.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_OV5647,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_OV5647.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_IMX219,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX219.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_IMX708,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX708.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_IMX462,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX462.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_IMX415,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX415.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_IMX477,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX477.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_5_IMX519,
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_5_IMX519.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_ROCK_5_OHD_Jaguar,
        kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar.data(),
        kCameraResolutions_X_CAM_TYPE_ROCK_5_OHD_Jaguar.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_3_HDMI_IN,
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_HDMI_IN.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_3_OV5647,
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_OV5647.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_3_IMX219,
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX219.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_3_IMX708,
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX708.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_3_IMX462,
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX462.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCK_3_IMX519,
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCK_3_IMX519.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_ROCK_3_OHD_Jaguar,
        kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar.data(),
        kCameraResolutions_X_CAM_TYPE_ROCK_3_OHD_Jaguar.size()},
    CameraResolutionEntry{
        X_CAM_TYPE_NVIDIA_XAVIER_IMX577,
        kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577.data(),
        kCameraResolutions_X_CAM_TYPE_NVIDIA_XAVIER_IMX577.size()},
    CameraResolutionEntry{X_CAM_TYPE_QC_IMX577,
                          kCameraResolutions_X_CAM_TYPE_QC_IMX577.data(),
                          kCameraResolutions_X_CAM_TYPE_QC_IMX577.size()},
    CameraResolutionEntry{X_CAM_TYPE_QC_OV9282,
                          kCameraResolutions_X_CAM_TYPE_QC_OV9282.data(),
                          kCameraResolutions_X_CAM_TYPE_QC_OV9282.size()},
    CameraResolutionEntry{X_CAM_TYPE_ORQA_HORNET,
                          kCameraResolutions_X_CAM_TYPE_ORQA_HORNET.data(),
                          kCameraResolutions_X_CAM_TYPE_ORQA_HORNET.size()},
    CameraResolutionEntry{X_CAM_TYPE_ORQA_JAGUAR,
                          kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR.data(),
                          kCameraResolutions_X_CAM_TYPE_ORQA_JAGUAR.size()},
    CameraResolutionEntry{X_CAM_TYPE_ORQA_REKINDLE,
                          kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE.data(),
                          kCameraResolutions_X_CAM_TYPE_ORQA_REKINDLE.size()},
    CameraResolutionEntry{X_CAM_TYPE_NXP_IMX8_V4L2,
                          kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2.data(),
                          kCameraResolutions_X_CAM_TYPE_NXP_IMX8_V4L2.size()},
    CameraResolutionEntry{X_CAM_TYPE_ROCKCHIP_RV110X,
                          kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X.data(),
                          kCameraResolutions_X_CAM_TYPE_ROCKCHIP_RV110X.size()},
};

inline const CameraResolutionEntry* find_camera_resolutions(int camera_type) {
  for (const auto& entry : kCameraResolutionEntries) {
    if (entry.type == camera_type) {
      return &entry;
    }
  }
  return nullptr;
}

inline constexpr std::array kManufacturer_USB_Cameras = {
    CameraUiEntry{X_CAM_TYPE_USB_INFIRAY, "INFIRAY USB"},
    CameraUiEntry{X_CAM_TYPE_USB_INFIRAY_T2, "INFIRAY USB T2"},
    CameraUiEntry{X_CAM_TYPE_USB_INFIRAY_P2_PRO, "INFIRAY USB P2 Pro"},
    CameraUiEntry{X_CAM_TYPE_USB_INFIRAY_X2, "INFIRAY USB X2"},
    CameraUiEntry{X_CAM_TYPE_USB_FLIR_VUE, "FLIR_VUE"},
    CameraUiEntry{X_CAM_TYPE_USB_FLIR_BOSON, "FLIR_BOSON"},
    CameraUiEntry{X_CAM_TYPE_USB_GENERIC, "EXP USB GENERIC"},
};

inline constexpr ManufacturerEntry kManufacturer_USB = {
    "USB", kManufacturer_USB_Cameras.data(), kManufacturer_USB_Cameras.size()};

inline constexpr std::array kManufacturer_DEBUG_Cameras = {
    CameraUiEntry{X_CAM_TYPE_DUMMY_SW, "Dummy (debug)"},
    CameraUiEntry{X_CAM_TYPE_EXTERNAL, "External (DEV)"},
    CameraUiEntry{X_CAM_TYPE_DEVELOPMENT_FILESRC, "DEV Filecamera"},
};

inline constexpr ManufacturerEntry kManufacturer_DEBUG = {
    "DEV/DEBUG", kManufacturer_DEBUG_Cameras.data(),
    kManufacturer_DEBUG_Cameras.size()};

inline constexpr std::array kManufacturer_DISABLE_Cameras = {
    CameraUiEntry{X_CAM_TYPE_DISABLED, "DISABLE"},
};

inline constexpr ManufacturerEntry kManufacturer_DISABLE = {
    "DISABLE", kManufacturer_DISABLE_Cameras.data(),
    kManufacturer_DISABLE_Cameras.size()};

inline constexpr std::array kManufacturer_RPI_ARDUCAM_Cameras = {
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708,
                  "SKYMASTERHDR"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519,
                  "SKYVISIONPRO"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M, "IMX477m"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462, "IMX462"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327, "IMX327"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX290, "IMX290"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI,
                  "IMX462_LOWLIGHT_MINI"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662, "IMX662"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415, "IMX415 4K"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_ARDUCAM = {
    "ARDUCAM", kManufacturer_RPI_ARDUCAM_Cameras.data(),
    kManufacturer_RPI_ARDUCAM_Cameras.size()};

inline constexpr std::array kManufacturer_RPI_VEYE_Cameras = {
    CameraUiEntry{X_CAM_TYPE_RPI_V4L2_VEYE_2MP, "2MP"},
    CameraUiEntry{X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307, "CSIMX307"},
    CameraUiEntry{X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132, "CSSC132"},
    CameraUiEntry{X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM, "MVCAM"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_VEYE = {
    "VEYE", kManufacturer_RPI_VEYE_Cameras.data(),
    kManufacturer_RPI_VEYE_Cameras.size()};

inline constexpr std::array kManufacturer_RPI_RPIF_Cameras = {
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647, "V1 OV5647"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219, "V2 IMX219"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708, "V3 IMX708"},
    CameraUiEntry{X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477, "HQ IMX477"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_RPIF = {
    "RPI FOUNDATION", kManufacturer_RPI_RPIF_Cameras.data(),
    kManufacturer_RPI_RPIF_Cameras.size()};

inline constexpr std::array kManufacturer_RPI_HDMI_Cameras = {
    CameraUiEntry{X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI, "GENERIC HDMI to CSI"},
};

inline constexpr ManufacturerEntry kManufacturer_RPI_HDMI = {
    "HDMI TO CSI", kManufacturer_RPI_HDMI_Cameras.data(),
    kManufacturer_RPI_HDMI_Cameras.size()};

inline constexpr std::array kManufacturer_X20_HDZERO_Cameras = {
    CameraUiEntry{X_CAM_TYPE_X20_HDZERO_GENERIC, "GENERIC"},
};

inline constexpr ManufacturerEntry kManufacturer_X20_HDZERO = {
    "HDZERO", kManufacturer_X20_HDZERO_Cameras.data(),
    kManufacturer_X20_HDZERO_Cameras.size()};

inline constexpr std::array kManufacturer_X20_RUNCAM_Cameras = {
    CameraUiEntry{X_CAM_TYPE_X20_HDZERO_RUNCAM_V1, "RUNCAM V1"},
    CameraUiEntry{X_CAM_TYPE_X20_HDZERO_RUNCAM_V2, "RUNCAM V2"},
    CameraUiEntry{X_CAM_TYPE_X20_HDZERO_RUNCAM_V3, "RUNCAM V3"},
    CameraUiEntry{X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90, "RUNCAM NANO 90"},
    CameraUiEntry{X_CAM_TYPE_X20_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_X20_RUNCAM = {
    "RUNCAM", kManufacturer_X20_RUNCAM_Cameras.data(),
    kManufacturer_X20_RUNCAM_Cameras.size()};

inline constexpr std::array kManufacturer_A733_ALLWINNER_Cameras = {
    CameraUiEntry{X_CAM_TYPE_A733_IMX415, "IMX415"},
    CameraUiEntry{X_CAM_TYPE_A733_IMX219, "IMX219"},
    CameraUiEntry{X_CAM_TYPE_A733_IMX214, "IMX214"},
};

inline constexpr ManufacturerEntry kManufacturer_A733_ALLWINNER = {
    "ALLWINNER", kManufacturer_A733_ALLWINNER_Cameras.data(),
    kManufacturer_A733_ALLWINNER_Cameras.size()};

inline constexpr std::array kManufacturer_ROCK3_ARDUCAM_Cameras = {
    CameraUiEntry{X_CAM_TYPE_ROCK_3_IMX462, "IMX462"},
    CameraUiEntry{X_CAM_TYPE_ROCK_3_IMX519, "IMX519"},
    CameraUiEntry{X_CAM_TYPE_ROCK_3_IMX708, "IMX708"},
    CameraUiEntry{X_CAM_TYPE_ROCK_3_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_ROCK3_ARDUCAM = {
    "Arducam", kManufacturer_ROCK3_ARDUCAM_Cameras.data(),
    kManufacturer_ROCK3_ARDUCAM_Cameras.size()};

inline constexpr std::array kManufacturer_ROCK5_A_GENERIC_Cameras = {
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX415, "IMX415"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX462, "IMX462"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX477, "IMX477"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX519, "IMX519"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_OV5647, "OV5647"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX219, "IMX219"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX708, "IMX708"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_ROCK5_A_GENERIC = {
    "Generic", kManufacturer_ROCK5_A_GENERIC_Cameras.data(),
    kManufacturer_ROCK5_A_GENERIC_Cameras.size()};

inline constexpr std::array kManufacturer_ROCK5_B_GENERIC_Cameras = {
    CameraUiEntry{X_CAM_TYPE_ROCK_5_HDMI_IN, "HDMI IN"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX415, "IMX415"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX462, "IMX462"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX477, "IMX477"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX519, "IMX519"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_OV5647, "OV5647"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX219, "IMX219"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_IMX708, "IMX708"},
    CameraUiEntry{X_CAM_TYPE_ROCK_5_OHD_Jaguar, "OpenHD Jaguar"},
};

inline constexpr ManufacturerEntry kManufacturer_ROCK5_B_GENERIC = {
    "Generic", kManufacturer_ROCK5_B_GENERIC_Cameras.data(),
    kManufacturer_ROCK5_B_GENERIC_Cameras.size()};

inline constexpr std::array kManufacturer_NVIDIA_LEOPARD_Cameras = {
    CameraUiEntry{X_CAM_TYPE_NVIDIA_XAVIER_IMX577, "IMX577"},
};

inline constexpr ManufacturerEntry kManufacturer_NVIDIA_LEOPARD = {
    "LEOPARD", kManufacturer_NVIDIA_LEOPARD_Cameras.data(),
    kManufacturer_NVIDIA_LEOPARD_Cameras.size()};

inline constexpr std::array kManufacturer_ORQA_Cameras = {
    CameraUiEntry{X_CAM_TYPE_ORQA_HORNET, "HORNET"},
    CameraUiEntry{X_CAM_TYPE_ORQA_JAGUAR, "JAGUAR"},
    CameraUiEntry{X_CAM_TYPE_ORQA_REKINDLE, "REKINDLE"},
};

inline constexpr ManufacturerEntry kManufacturer_ORQA = {
    "ORQA", kManufacturer_ORQA_Cameras.data(),
    kManufacturer_ORQA_Cameras.size()};

inline constexpr std::array kManufacturer_NXP_Cameras = {
    CameraUiEntry{X_CAM_TYPE_NXP_IMX8_V4L2, "V4L2 CSI"},
};

inline constexpr ManufacturerEntry kManufacturer_NXP = {
    "NXP", kManufacturer_NXP_Cameras.data(), kManufacturer_NXP_Cameras.size()};

inline constexpr std::array kManufacturer_LUCKFOX_Cameras = {
    CameraUiEntry{X_CAM_TYPE_ROCKCHIP_RV110X, "MIS5001"},
};

inline constexpr ManufacturerEntry kManufacturer_LUCKFOX = {
    "LUCKFOX", kManufacturer_LUCKFOX_Cameras.data(),
    kManufacturer_LUCKFOX_Cameras.size()};

inline constexpr std::array kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers = {
    kManufacturer_RPI_ARDUCAM, kManufacturer_RPI_VEYE, kManufacturer_RPI_RPIF,
    kManufacturer_RPI_HDMI,    kManufacturer_USB,      kManufacturer_DEBUG,
};

inline constexpr std::array kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers = {
    kManufacturer_RPI_ARDUCAM, kManufacturer_RPI_VEYE, kManufacturer_RPI_RPIF,
    kManufacturer_RPI_HDMI,    kManufacturer_USB,      kManufacturer_DEBUG,
};

inline constexpr std::array kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers = {
    kManufacturer_RPI_ARDUCAM, kManufacturer_RPI_VEYE, kManufacturer_RPI_RPIF,
    kManufacturer_RPI_HDMI,    kManufacturer_USB,      kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers = {
        kManufacturer_X20_HDZERO,
        kManufacturer_X20_RUNCAM,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers = {
        kManufacturer_A733_ALLWINNER,
        kManufacturer_USB,
        kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers = {
        kManufacturer_ROCK3_ARDUCAM,
        kManufacturer_USB,
        kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers = {
        kManufacturer_ROCK3_ARDUCAM,
        kManufacturer_USB,
        kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers = {
        kManufacturer_ROCK5_A_GENERIC,
        kManufacturer_USB,
        kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers = {
        kManufacturer_ROCK5_B_GENERIC,
        kManufacturer_USB,
        kManufacturer_DEBUG,
};

inline constexpr std::array kPlatform_X_PLATFORM_TYPE_X86_Manufacturers = {
    kManufacturer_USB,
    kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers = {
        kManufacturer_NVIDIA_LEOPARD,
        kManufacturer_USB,
        kManufacturer_DEBUG,
};

inline constexpr std::array kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers = {
    kManufacturer_ORQA,
    kManufacturer_USB,
    kManufacturer_DEBUG,
};

inline constexpr std::array kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers = {
    kManufacturer_NXP,
    kManufacturer_USB,
    kManufacturer_DEBUG,
};

inline constexpr std::array
    kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers = {
        kManufacturer_LUCKFOX,
};

inline constexpr std::array kPlatformCameraChoices = {
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_RPI_OLD,
        kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_RPI_OLD_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_RPI_4,
        kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_RPI_4_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_RPI_CM4,
        kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_RPI_CM4_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ALWINNER_X20,
        kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_ALWINNER_X20_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z,
        kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_ALWINNER_CUBIE_A7Z_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W,
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers
            .data(),
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_ZERO3W_Manufacturers
            .size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3,
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers
            .data(),
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3566_RADXA_CM3_Manufacturers
            .size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A,
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers
            .data(),
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_A_Manufacturers
            .size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B,
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers
            .data(),
        kPlatform_X_PLATFORM_TYPE_ROCKCHIP_RK3588_RADXA_ROCK5_B_Manufacturers
            .size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_X86, kPlatform_X_PLATFORM_TYPE_X86_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_X86_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_NVIDIA_XAVIER,
        kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_NVIDIA_XAVIER_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_ORQA,
        kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_ORQA_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_NXP_IMX8,
        kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_NXP_IMX8_Manufacturers.size()},
    PlatformCameraChoicesEntry{
        X_PLATFORM_TYPE_LUCKFOX_RV110X,
        kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers.data(),
        kPlatform_X_PLATFORM_TYPE_LUCKFOX_RV110X_Manufacturers.size()},
};

inline constexpr std::array kSecondaryManufacturers = {
    kManufacturer_DISABLE,
    kManufacturer_USB,
    kManufacturer_DEBUG,
};

inline constexpr std::size_t kSecondaryManufacturerCount =
    kSecondaryManufacturers.size();

inline constexpr std::array kFallbackManufacturers = {
    kManufacturer_DEBUG,
};

inline constexpr std::size_t kFallbackManufacturerCount =
    kFallbackManufacturers.size();

inline const PlatformCameraChoicesEntry* find_platform_camera_choices(
    int platform_type) {
  for (const auto& entry : kPlatformCameraChoices) {
    if (entry.platform_type == platform_type) {
      return &entry;
    }
  }
  return nullptr;
}

}  // namespace openhd::camera_registry

using openhd::camera_registry::X_CAM_TYPE_A733_IMX214;
using openhd::camera_registry::X_CAM_TYPE_A733_IMX219;
using openhd::camera_registry::X_CAM_TYPE_A733_IMX415;
using openhd::camera_registry::X_CAM_TYPE_DEVELOPMENT_FILESRC;
using openhd::camera_registry::X_CAM_TYPE_DISABLED;
using openhd::camera_registry::X_CAM_TYPE_DUMMY_SW;
using openhd::camera_registry::X_CAM_TYPE_EXTERNAL;
using openhd::camera_registry::X_CAM_TYPE_EXTERNAL_IP;
using openhd::camera_registry::X_CAM_TYPE_NVIDIA_XAVIER_IMX577;
using openhd::camera_registry::X_CAM_TYPE_NXP_IMX8_V4L2;
using openhd::camera_registry::X_CAM_TYPE_OPENIPC_GENERIC;
using openhd::camera_registry::X_CAM_TYPE_ORQA_HORNET;
using openhd::camera_registry::X_CAM_TYPE_ORQA_JAGUAR;
using openhd::camera_registry::X_CAM_TYPE_ORQA_REKINDLE;
using openhd::camera_registry::X_CAM_TYPE_QC_IMX577;
using openhd::camera_registry::X_CAM_TYPE_QC_OV9282;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_HDMI_IN;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX219;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX462;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX519;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_IMX708;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_OV5647;
using openhd::camera_registry::X_CAM_TYPE_ROCK_3_VEYE;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_HDMI_IN;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX219;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX415;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX462;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX477;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX519;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_IMX708;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_ROCK_5_OV5647;
using openhd::camera_registry::X_CAM_TYPE_ROCKCHIP_RV110X;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX290;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX327;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX415;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462;
using openhd::camera_registry::
    X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX462_LOWLIGHT_MINI;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX477M;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_IMX662;
using openhd::camera_registry::
    X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYMASTERHDR_IMX708;
using openhd::camera_registry::
    X_CAM_TYPE_RPI_LIBCAMERA_ARDUCAM_SKYVISIONPRO_IMX519;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_HQ_IMX477;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V1_OV5647;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V2_IMX219;
using openhd::camera_registry::X_CAM_TYPE_RPI_LIBCAMERA_RPIF_V3_IMX708;
using openhd::camera_registry::X_CAM_TYPE_RPI_MMAL_HDMI_TO_CSI;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_2MP;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_CSIMX307;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_CSSC132;
using openhd::camera_registry::X_CAM_TYPE_RPI_V4L2_VEYE_MVCAM;
using openhd::camera_registry::X_CAM_TYPE_USB_FLIR_BOSON;
using openhd::camera_registry::X_CAM_TYPE_USB_FLIR_VUE;
using openhd::camera_registry::X_CAM_TYPE_USB_GENERIC;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY_P2_PRO;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY_T2;
using openhd::camera_registry::X_CAM_TYPE_USB_INFIRAY_X2;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_GENERIC;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_NANO_90;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_V1;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_V2;
using openhd::camera_registry::X_CAM_TYPE_X20_HDZERO_RUNCAM_V3;
using openhd::camera_registry::X_CAM_TYPE_X20_OHD_Jaguar;
using openhd::camera_registry::X_CAM_TYPE_X21_OHD_Jaguar;
