add_subdirectory(00_common)
add_subdirectory(01_basic_info)
add_subdirectory(02_pair_manager)
add_subdirectory(03_link_monitor)
add_subdirectory(04_link_config)
add_subdirectory(05_config_file)
add_subdirectory(06_minidb_config)
add_subdirectory(07_uart_config)
add_subdirectory(08_socket_transfer)
add_subdirectory(09_project_event)
