import kconfiglib
import sys
import os
import argparse

def main():
    parser = argparse.ArgumentParser(description='Kconfig to CMake/C++ bridge')
    parser.add_argument('--kconfig', default='Kconfig', help='Root Kconfig file')
    parser.add_argument('--config', default='.config', help='Input .config file')
    parser.add_argument('--out-header', default='autoconf.h', help='Output C++ header')
    parser.add_argument('--out-cmake', default='kconfig.cmake', help='Output CMake file')
    args = parser.parse_args()

    if not os.path.exists(args.kconfig):
        print(f"Error: {args.kconfig} not found")
        sys.exit(1)

    kconf = kconfiglib.Kconfig(args.kconfig)

    if os.path.exists(args.config):
        kconf.load_config(args.config)
    else:
        print(f"Warning: {args.config} not found, using defaults")

    # Write autoconf.h
    kconf.write_autoconf(args.out_header)
    print(f"Generated {args.out_header}")

    # Write kconfig.cmake
    with open(args.out_cmake, "w") as f:
        f.write("# Generated by kconfig.py - DO NOT EDIT\n\n")
        for sym in kconf.unique_defined_syms:
            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                val = "ON" if sym.str_value == "y" else "OFF"
                f.write(f"set({sym.name} {val} CACHE INTERNAL \"\")\n")
            elif sym.type == kconfiglib.INT:
                f.write(f"set({sym.name} {sym.str_value} CACHE INTERNAL \"\")\n")
            elif sym.type == kconfiglib.HEX:
                f.write(f"set({sym.name} 0x{sym.str_value} CACHE INTERNAL \"\")\n")
            elif sym.type == kconfiglib.STRING:
                f.write(f"set({sym.name} \"{sym.str_value}\" CACHE INTERNAL \"\")\n")
    print(f"Generated {args.out_cmake}")

if __name__ == "__main__":
    main()
