import kconfiglib
import sys
import os
import argparse

def main():
    parser = argparse.ArgumentParser(description='Kconfig to CMake/C++ bridge')
    parser.add_argument('--kconfig', default='Kconfig', help='Root Kconfig file')
    parser.add_argument('--config', default='.config', help='Input .config file')
    parser.add_argument('--out-header', default='autoconf.h', help='Output C++ header')
    parser.add_argument('--out-cmake', default='kconfig.cmake', help='Output CMake file')
    parser.add_argument('--set', nargs=2, action='append', metavar=('SYMBOL', 'VALUE'), help='Set symbol value')
    args = parser.parse_args()

    if not os.path.exists(args.kconfig):
        print(f"Error: {args.kconfig} not found")
        sys.exit(1)

    # Set srctree environment variable to the directory containing the root Kconfig
    # This allows Kconfiglib to resolve 'source' paths correctly regardless of CWD.
    kconfig_abs_path = os.path.abspath(args.kconfig)
    kconfig_dir = os.path.dirname(kconfig_abs_path)
    os.environ["srctree"] = kconfig_dir

    kconf = kconfiglib.Kconfig(kconfig_abs_path)

    if os.path.exists(args.config):
        kconf.load_config(args.config)
    else:
        print(f"Warning: {args.config} not found, using defaults")

    # Apply overrides
    if args.set:
        for sym_name, value in args.set:
            if sym_name in kconf.syms:
                kconf.syms[sym_name].set_value(value)
            else:
                print(f"Warning: Symbol {sym_name} not found in Kconfig")

    # Save the updated .config
    kconf.write_config(args.config)

    # Write autoconf.h
    kconf.write_autoconf(args.out_header)
    print(f"Generated {args.out_header}")

    # Write kconfig.cmake
    with open(args.out_cmake, "w") as f:
        f.write("# Generated by kconfig.py - DO NOT EDIT\n\n")
        for sym in kconf.unique_defined_syms:
            # Prepend CONFIG_ to match autoconf.h and standard Kconfig behavior
            name = f"CONFIG_{sym.name}"
            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                val = "ON" if sym.str_value == "y" else "OFF"
                f.write(f"set({name} {val} CACHE INTERNAL \"\" FORCE)\n")
            elif sym.type == kconfiglib.INT:
                f.write(f"set({name} {sym.str_value} CACHE INTERNAL \"\" FORCE)\n")
            elif sym.type == kconfiglib.HEX:
                f.write(f"set({name} 0x{sym.str_value} CACHE INTERNAL \"\" FORCE)\n")
            elif sym.type == kconfiglib.STRING:
                f.write(f"set({name} \"{sym.str_value}\" CACHE INTERNAL \"\" FORCE)\n")
    print(f"Generated {args.out_cmake}")

if __name__ == "__main__":
    main()
