name: Build SIYI plugin

on:
  workflow_dispatch:
  push:
    branches:
      - openhd-3.0

permissions:
  contents: read

jobs:
  build-and-publish:
    uses: OpenHD-Technologies/openhd-plugin-siyi/.github/workflows/build.yml@main
    with:
      openhd_ref: ${{ github.sha }}
      plugin_ref: main
      cloudsmith_repo: dev-release
      publish: true
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
