name: build_package_x86_22.04

on:
  push:
    branches:
      - "2.6-evo-AI"
      
env:
  # CMake 빌드 유형 설정
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Environment Setup
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
              
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update System and Install Base Libs
        run: |
          sudo apt update
          # grub 관련 업데이트로 인한 멈춤 방지
          sudo apt-mark hold grub-efi-amd64-signed
          sudo apt upgrade -y
          sudo apt install libpoco-dev -y

      - name: Install Dependencies
        run: |
          sudo ./install_build_dep.sh ubuntu-x86
          
      - name: Build and Package
        run: |
          # x86_64용 Ubuntu Jammy 패키지 생성
          sudo ./package.sh standard x86_64 ubuntu jammy
          ls -l *.deb

      - name: Upload to Github
        # 빌드된 패키지와 로그 파일을 GitHub Artifacts에 업로드합니다.
        uses: actions/upload-artifact@v4
        with:
          name: OpenHD-x86_64-Ubuntu-Jammy  # 다운로드 시 식별하기 쉬운 이름
          path: |
            *.deb
            *.log
          if-no-files-found: error
