name: build_package_jetson

on:
  push:
    branches: ["2.3-evo"]
    paths-ignore:
      - '**.yml'
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 10
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Emulating Jetson
      id: qemu
      uses: pguyot/arm-runner-action@v2.5.2
      with:
        base_image: https://openhd-images.fra1.cdn.digitaloceanspaces.com/BaseImages/Open.HD-2.1-05221841-jetson-nano-4gb-bionic.img.zip
        cpu: cortex-a53
        bootpartition:
        rootpartition: 1
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: OpenHD
        import_github_env: true
        commands: |
          mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
          cd /opt
          cd OpenHD
          sudo apt update
          mkdir -p /usr/local/share/openhd/
          touch /usr/local/share/openhd/joyconfig.txt
          sudo ./install_build_dep.sh jetson
          chown -R root:root /opt
          git clone https://github.com/gabime/spdlog.git
          cd spdlog
          git checkout v1.8.1
          mkdir build && cd build
          cmake .. && make -j
          make install
          cd ../../
          sudo ./package.sh arm64 ubuntu bionic


    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo"
        distro: "ubuntu"
        release: "bionic"
        republish: "true" # needed ONLY if version is not changing
        file: "OpenHD/*.deb"
