name: build_package_x20_debian

on:
  push:
   branches:
      - "2.5-evo"
      - "dev-release"
      - "release"

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          overprovision-lvm: 'true'
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    
             
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Building OpenHD in CHROOT
        run: |
          git clone -b x20 https://github.com/OpenHD/OpenHD-ChrootCompiler /opt/OpenHD-ChrootCompiler
          mkdir -p /opt/OpenHD-ChrootCompiler/additionalFiles
          git clone https://github.com/OpenHD/OpenHD -b ${{ github.ref_name }} /opt/OpenHD-ChrootCompiler/additionalFiles/ --recursive
          echo $CLOUDSMITH_API_KEY > /opt/OpenHD-ChrootCompiler/additionalFiles/cloudsmith_api_key.txt
          echo "true" > /opt/OpenHD-ChrootCompiler/additionalFiles/custom.txt
          echo "armhf" > /opt/OpenHD-ChrootCompiler/additionalFiles/arch.txt
          echo "debian" > /opt/OpenHD-ChrootCompiler/additionalFiles/distro.txt
          echo "bullseye" > /opt/OpenHD-ChrootCompiler/additionalFiles/flavor.txt
          echo "${{ github.ref_name }}" > /opt/OpenHD-ChrootCompiler/additionalFiles/repo.txt

          cd /opt/OpenHD-ChrootCompiler/
          sudo apt update
          sudo bash install_dep.sh
          sudo bash ./build.sh x20 $API_KEY debian bullseye
      
      - name: debug
        run:
          ls -a
          cp out/* .

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "OpenHD"
          path: |
            *.deb