name: build_package_x86_22.04

on:
  push:
   branches:
      - "2.6-evo"
      - "dev-release"
      - "release"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
              
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: fix Repository
        run: |
          sudo apt update
          sudo apt-mark hold grub-efi-amd64-signed
          sudo apt upgrade -y
          sudo apt install libpoco-dev -y
      - name: Install Dependencies
        run: |
          sudo ./install_build_dep.sh ubuntu-x86
          
      - name: Build with make
        run: |
          sudo ./package.sh standard x86_64 ubuntu jammy
          ls -a

      - name: Upload to Github
        uses: 'actions/upload-artifact@v4'
        with:
          name: "OpenHD"
          path: |
            *.deb
            *.log
          if-no-files-found: error

      - name: Push
        id: push
        if: github.ref_name == 'release' || github.ref_name == 'dev-release'
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: ${{ github.ref_name }}
          distro: "ubuntu"
          release: "jammy"
          republish: "true" # needed ONLY if version is not changing
          file: "*.deb"