# Run clang-tidy
name: Clang-tidy

on:
  push:
    branches-ignore:
      - release
      - dev-release

jobs:

  validate_codestyle_clang_format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Dependencies
        run: |
          sudo apt install clang-format
          
      - name: Format code
        run: |
          cd OpenHD
          ./run_clang_format.sh f
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Apply clang-format"
          file_pattern: "**/*.cpp **/*.h **/*.hpp"
